# Site settings
title: Shihanmax's Blog
SEOTitle: 马诗涵的博客 | Shihanmax's Blog
header-img: http://qiniu.shihanmax.top/20210405144942_cO1WBY_1.jpeg
email: shihanmax@foxmail.com
description: "Machine Learning & Dev Engineer"
keyword: "机器学习,自然语言处理"
url: "http://shihanmax.top"            # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
host: "*"

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     huxpro
# zhihu_username:     huxpro
# github_username:    shihanmax 
# twitter_username:   huxpro
# facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate, jekyll-redirect-from, jekyll-relative-links]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


relative_links:
  enabled:     true
  collections: false

# Disqus settings
disqus_username: false


# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar:  true  # whether or not using Sidebar.
sidebar-about-description: "一个脱离了高级趣味的码农"  # 马诗涵，机器学习&自然语言处理算法工程师<br>I am an algorithm engineer focusing on machine learning and natural language processing.
sidebar-avatar: http://qiniu.shihanmax.top/20210526180809_mWrg2E_%E6%88%AA%E5%B1%8F2021-05-26%2018.05.48.jpeg   # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true 



# Friends
# friends: [
#     {
#     #     title: "Shihanmax",
#     #     href: "http://shihanmax.top"
#     # }
# ]
