# Site settings
title: Shihanmax's blog
description: >
    Shihanmax's blog
author: Shihanmax
email: shihanmax@foxmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shihanmax.github.io" # the base hostname & protocol for your site
# twitter_username: YourTwitterNo
github_username:  shihanmax

# disqus_shortname: Test1

# Build settings
include: [_pages]
highlighter: rouge
# syntax_highlighter: rouge

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
      theme: solarized

future: true
permalink: /:year/:month/:title
sass:
    style: compressed

paginate: 15
paginate_path: "blog/page:num/"
plugins: [jekyll-paginate, jemoji, jekyll-sitemap]
collections:
  protected: